# yazi.toml
[mgr]
show_hidden = true


[opener]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'mpv %*', orphan = true, for = "windows" },
]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = "%EDITOR% %*", block = true, for = "windows" },
]
